// AUTO-GENERATED by scripts/gen-mock.js — do not edit by hand.
// Re-run `node scripts/gen-mock.js` after changing the songs in src/eample-song.
import type { Track, Album, Artist, Playlist } from "./cloudflare";

// Set to false to use the real Cloudflare backend instead of these sample songs.
export const USE_MOCK_DATA = false;

export const MOCK_TRACKS: Track[] = [
  {
    "id": "niki-lowkey-0",
    "title": "lowkey",
    "artist": "Niki",
    "album": "lowkey",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/01%20-%20lowkey.flac",
    "cover_url": "/covers/album-niki-lowkey.jpg",
    "genre": "Soul",
    "duration": 171,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-lose-1",
    "title": "Lose",
    "artist": "Niki",
    "album": "MOONCHILD",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/03%20-%20NIKI%20-%20Lose(Explicit).flac",
    "cover_url": "/covers/album-niki-moonchild.jpg",
    "year": 2020,
    "duration": 256,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-every-summertime-2",
    "title": "Every Summertime",
    "artist": "Niki",
    "album": "Shang-Chi and The Legend of The Ten Rings: The Album",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/034%20-%20Niki%20-%20Every%20Summertime.flac",
    "year": 2021,
    "genre": "Films/Games / Film Scores",
    "duration": 216,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-pools-3",
    "title": "Pools",
    "artist": "Niki",
    "album": "Zephyr",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/07%20-%20NIKI%20-%20Pools(Explicit).flac",
    "cover_url": "/covers/album-niki-zephyr.jpg",
    "year": 2018,
    "duration": 209,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "dj-snake-run-it-4",
    "title": "Run It",
    "artist": "DJ Snake",
    "album": "Shang-Chi and The Legend of The Ten Rings: The Album",
    "category": "DJ Snake",
    "file_url": "/api/local-audio/NIKI/14%20-%20DJ%20Snake,%20Rick%20Ross,%20Rich%20Brian%20-%20Run%20It.flac",
    "cover_url": "/covers/album-dj-snake-shang-chi-and-the-legend-of-the-ten-ring.jpg",
    "year": 2021,
    "duration": 163,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-blue-moon-5",
    "title": "Blue Moon",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Blue%20Moon%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 226,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-buzz-6",
    "title": "Buzz",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Buzz%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 176,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-colossal-loss-7",
    "title": "Colossal Loss",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Colossal%20Loss%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 219,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-did-you-like-her-in-the-morning-8",
    "title": "Did You Like Her In The Morning?",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Did%20You%20Like%20Her%20In%20The%20Morning%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 217,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-focus-9",
    "title": "Focus",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Focus%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 206,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-heirloom-pain-10",
    "title": "Heirloom Pain",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Heirloom%20Pain%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 184,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-magnets-11",
    "title": "Magnets",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Magnets%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 217,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-nothing-can-12",
    "title": "Nothing Can",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Nothing%20Can%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 223,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-paths-13",
    "title": "Paths",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Paths%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 190,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-strong-girl-14",
    "title": "Strong Girl",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Strong%20Girl%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 215,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-take-care-15",
    "title": "Take Care",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Take%20Care%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 153,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-too-much-of-a-good-thing-16",
    "title": "Too Much Of A Good Thing",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Too%20Much%20Of%20A%20Good%20Thing%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 172,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "niki-tsunami-17",
    "title": "Tsunami",
    "artist": "Niki",
    "album": "Buzz",
    "category": "Niki",
    "file_url": "/api/local-audio/NIKI/Tsunami%20-%20Niki.flac",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "year": 2024,
    "genre": "Alternative & Indie",
    "duration": 231,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "bbno-edamame-18",
    "title": "edamame",
    "artist": "bbno$",
    "album": "edamame",
    "category": "bbno$",
    "file_url": "/api/local-audio/Rich%20Brian/01%20-%20bbno$,%20Rich%20Brian%20-%20edamame(Explicit).flac",
    "cover_url": "/covers/album-bbno-edamame.jpg",
    "year": 2021,
    "duration": 134,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "rich-brian-amen-19",
    "title": "Amen",
    "artist": "Rich Brian",
    "album": "Amen",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/01.%20Amen.flac",
    "cover_url": "/covers/album-rich-brian-amen.jpg",
    "year": 2018,
    "genre": "Rap",
    "duration": 117,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "bbno-edamame-20",
    "title": "edamame",
    "artist": "bbno$",
    "album": "edamame",
    "category": "bbno$",
    "file_url": "/api/local-audio/Rich%20Brian/01.%20edamame.flac",
    "year": 2021,
    "genre": "Rap",
    "duration": 134,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "rich-brian-cold-21",
    "title": "Cold",
    "artist": "Rich Brian",
    "album": "Amen",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/02%20Cold%20-%20Rich%20Brian.flac",
    "cover_url": "/covers/album-rich-brian-amen.jpg",
    "year": 2018,
    "duration": 228,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "rich-brian-new-tooth-22",
    "title": "New Tooth",
    "artist": "Rich Brian",
    "album": "Brightside",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/1.%20New%20Tooth.flac",
    "cover_url": "/covers/album-rich-brian-brightside.jpg",
    "year": 2022,
    "genre": "Hip-Hop/Rap",
    "duration": 220,
    "bit_depth": 24,
    "sample_rate": 96000,
    "play_count": 0
  },
  {
    "id": "rich-brian-lagoon-23",
    "title": "Lagoon",
    "artist": "Rich Brian",
    "album": "Brightside",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/2.%20Lagoon.flac",
    "cover_url": "/covers/album-rich-brian-brightside.jpg",
    "year": 2022,
    "genre": "Hip-Hop/Rap",
    "duration": 170,
    "bit_depth": 24,
    "sample_rate": 96000,
    "play_count": 0
  },
  {
    "id": "rich-brian-getcho-mans-24",
    "title": "Getcho Mans",
    "artist": "Rich Brian",
    "album": "Brightside",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/3.%20Getcho%20Mans.flac",
    "cover_url": "/covers/album-rich-brian-brightside.jpg",
    "year": 2022,
    "genre": "Hip-Hop/Rap",
    "duration": 211,
    "bit_depth": 24,
    "sample_rate": 96000,
    "play_count": 0
  },
  {
    "id": "rich-brian-kids-25",
    "title": "Kids",
    "artist": "Rich Brian",
    "album": "The Sailor",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/4.%20Kids.flac",
    "cover_url": "/covers/album-rich-brian-the-sailor.jpg",
    "year": 2019,
    "genre": "Hip-Hop/Rap",
    "duration": 270,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "rich-brian-sunny-26",
    "title": "Sunny",
    "artist": "Rich Brian",
    "album": "Brightside",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/4.%20Sunny.flac",
    "cover_url": "/covers/album-rich-brian-brightside.jpg",
    "year": 2022,
    "genre": "Hip-Hop/Rap",
    "duration": 160,
    "bit_depth": 24,
    "sample_rate": 96000,
    "play_count": 0
  },
  {
    "id": "rich-brian-doa-27",
    "title": "DOA",
    "artist": "Rich Brian",
    "album": "1999",
    "category": "Rich Brian",
    "file_url": "/api/local-audio/Rich%20Brian/5.%20DOA.flac",
    "cover_url": "/covers/album-rich-brian-1999.jpg",
    "year": 2020,
    "genre": "Hip-Hop/Rap",
    "duration": 161,
    "bit_depth": 24,
    "sample_rate": 44100,
    "play_count": 0
  },
  {
    "id": "88rising-rich-brian-tokyo-drift-freestyle-28",
    "title": "RICH BRIAN TOKYO DRIFT FREESTYLE",
    "artist": "88rising",
    "album": "Singles",
    "category": "88rising",
    "file_url": "/api/local-audio/Rich%20Brian/RICH%20BRIAN%20TOKYO%20DRIFT%20FREESTYLE%20%5BVnSWx5_3W7M%5D.m4a",
    "duration": 143,
    "bit_depth": 16,
    "sample_rate": 44100,
    "play_count": 0
  }
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    "id": "pl-0",
    "name": "Niki"
  },
  {
    "id": "pl-1",
    "name": "DJ Snake"
  },
  {
    "id": "pl-2",
    "name": "bbno$"
  },
  {
    "id": "pl-3",
    "name": "Rich Brian"
  },
  {
    "id": "pl-4",
    "name": "88rising"
  }
];

export const MOCK_CATEGORY_COUNTS: { category: string; count: number }[] = [
  {
    "category": "Niki",
    "count": 17
  },
  {
    "category": "DJ Snake",
    "count": 1
  },
  {
    "category": "bbno$",
    "count": 2
  },
  {
    "category": "Rich Brian",
    "count": 8
  },
  {
    "category": "88rising",
    "count": 1
  }
];

export const MOCK_ALBUMS: Album[] = [
  {
    "name": "1999",
    "trackCount": 1,
    "artist": "Rich Brian",
    "cover_url": "/covers/album-rich-brian-1999.jpg",
    "source": "embedded"
  },
  {
    "name": "lowkey",
    "trackCount": 1,
    "artist": "Niki",
    "cover_url": "/covers/album-niki-lowkey.jpg",
    "source": "embedded"
  },
  {
    "name": "MOONCHILD",
    "trackCount": 1,
    "artist": "Niki",
    "cover_url": "/covers/album-niki-moonchild.jpg",
    "source": "embedded"
  },
  {
    "name": "Shang-Chi and The Legend of The Ten Rings: The Album",
    "trackCount": 2,
    "artist": "Niki",
    "source": "none"
  },
  {
    "name": "Zephyr",
    "trackCount": 1,
    "artist": "Niki",
    "cover_url": "/covers/album-niki-zephyr.jpg",
    "source": "embedded"
  },
  {
    "name": "Buzz",
    "trackCount": 13,
    "artist": "Niki",
    "cover_url": "/covers/album-niki-buzz.jpg",
    "source": "embedded"
  },
  {
    "name": "edamame",
    "trackCount": 2,
    "artist": "bbno$",
    "cover_url": "/covers/album-bbno-edamame.jpg",
    "source": "embedded"
  },
  {
    "name": "Amen",
    "trackCount": 2,
    "artist": "Rich Brian",
    "cover_url": "/covers/album-rich-brian-amen.jpg",
    "source": "embedded"
  },
  {
    "name": "Brightside",
    "trackCount": 4,
    "artist": "Rich Brian",
    "cover_url": "/covers/album-rich-brian-brightside.jpg",
    "source": "embedded"
  },
  {
    "name": "The Sailor",
    "trackCount": 1,
    "artist": "Rich Brian",
    "cover_url": "/covers/album-rich-brian-the-sailor.jpg",
    "source": "embedded"
  },
  {
    "name": "Singles",
    "trackCount": 1,
    "artist": "88rising",
    "source": "none"
  }
];

export const MOCK_ARTISTS: Artist[] = [
  {
    "name": "Niki",
    "trackCount": 17,
    "albumCount": 5,
    "image_url": "/covers/album-niki-lowkey.jpg"
  },
  {
    "name": "DJ Snake",
    "trackCount": 1,
    "albumCount": 1,
    "image_url": "/covers/album-dj-snake-shang-chi-and-the-legend-of-the-ten-ring.jpg"
  },
  {
    "name": "bbno$",
    "trackCount": 2,
    "albumCount": 1,
    "image_url": "/covers/album-bbno-edamame.jpg"
  },
  {
    "name": "Rich Brian",
    "trackCount": 8,
    "albumCount": 4,
    "image_url": "/covers/album-rich-brian-amen.jpg"
  },
  {
    "name": "88rising",
    "trackCount": 1,
    "albumCount": 1
  }
];
