// Generates src/lib/mockData.ts from the songs in src/eample-song.
// - Extracts metadata (title/artist/album/year/genre/duration) from each file
// - Extracts embedded cover art, compresses it, saves to public/covers/
// - Uses an album cover as each artist's profile photo
// Run: node scripts/gen-mock.js   (or: npm run gen-mock)
const fs = require("fs");
const path = require("path");
const mm = require("music-metadata");
const sharp = require("sharp");

const ROOT = path.join(__dirname, "..");
const SONG_DIR = path.join(ROOT, "src", "eample-song");
const COVER_OUT = path.join(ROOT, "public", "covers");
const AUDIO_RE = /\.(flac|ogg|m4a|mp3|wav)$/i;

const slug = (s) =>
  String(s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "x";

(async () => {
  fs.rmSync(COVER_OUT, { recursive: true, force: true });
  fs.mkdirSync(COVER_OUT, { recursive: true });

  const tracks = [];
  const albumCover = {};      // "artist::album" -> "/covers/x.jpg"
  const artistCover = {};     // artist -> "/covers/x.jpg" (first album cover seen)
  const canonicalArtist = {}; // lowercased name -> first-seen casing (merges "Niki"/"NIKI")

  const folders = fs.readdirSync(SONG_DIR, { withFileTypes: true }).filter((d) => d.isDirectory());
  for (const folder of folders) {
    const dir = path.join(SONG_DIR, folder.name);
    const files = fs.readdirSync(dir).filter((f) => AUDIO_RE.test(f));
    for (const file of files) {
      const full = path.join(dir, file);
      let meta;
      try {
        meta = await mm.parseFile(full);
      } catch (e) {
        console.warn("  skip (parse failed):", file, e.message);
        continue;
      }
      const c = meta.common, fmt = meta.format;
      const title = c.title || file.replace(AUDIO_RE, "");
      let artist = (c.artist || folder.name).trim();
      const aKey = artist.toLowerCase();
      if (!canonicalArtist[aKey]) canonicalArtist[aKey] = artist;
      artist = canonicalArtist[aKey]; // collapse casing variants to one name
      const album = c.album || "Singles";
      // Key covers/albums by album NAME only (matches the real getAlbums, which
      // GROUP BYs album) so compilation albums with multiple artists don't become
      // duplicate entries with the same name.
      const albumKey = album;

      // Save one compressed cover per album.
      let coverUrl;
      if (c.picture && c.picture[0]) {
        if (!albumCover[albumKey]) {
          const cname = `album-${slug(artist)}-${slug(album)}.jpg`;
          try {
            await sharp(c.picture[0].data)
              .rotate()
              .resize(800, 800, { fit: "inside", withoutEnlargement: true })
              .jpeg({ quality: 82 })
              .toFile(path.join(COVER_OUT, cname));
            albumCover[albumKey] = `/covers/${cname}`;
          } catch (e) {
            console.warn("  cover failed:", album, e.message);
          }
        }
        coverUrl = albumCover[albumKey];
        if (coverUrl && !artistCover[artist]) artistCover[artist] = coverUrl;
      }

      tracks.push({
        id: `${slug(artist)}-${slug(title)}-${tracks.length}`,
        title,
        artist,
        album,
        category: artist,
        file_url: "/api/local-audio/" + encodeURI(`${folder.name}/${file}`),
        cover_url: coverUrl,
        year: c.year,
        genre: c.genre && c.genre[0] ? c.genre[0] : undefined,
        duration: fmt.duration ? Math.round(fmt.duration) : undefined,
        bit_depth: fmt.bitsPerSample || undefined,
        sample_rate: fmt.sampleRate || undefined,
        play_count: 0,
      });
    }
  }

  // Derive albums.
  const albumMap = {};
  for (const t of tracks) {
    const k = t.album;
    if (!albumMap[k]) {
      albumMap[k] = { name: t.album, trackCount: 0, artist: t.artist, cover_url: t.cover_url, source: t.cover_url ? "embedded" : "none" };
    }
    albumMap[k].trackCount++;
  }
  const albums = Object.values(albumMap);

  // Derive artists (profile photo = an album cover).
  const artistMap = {};
  for (const t of tracks) {
    if (!artistMap[t.artist]) artistMap[t.artist] = { name: t.artist, trackCount: 0, albums: new Set(), image_url: artistCover[t.artist] };
    artistMap[t.artist].trackCount++;
    artistMap[t.artist].albums.add(t.album);
  }
  const artists = Object.values(artistMap).map((a) => ({
    name: a.name,
    trackCount: a.trackCount,
    albumCount: a.albums.size,
    image_url: a.image_url,
  }));

  const playlists = artists.map((a, i) => ({ id: `pl-${i}`, name: a.name }));
  const categoryCounts = artists.map((a) => ({ category: a.name, count: a.trackCount }));

  const J = (v) => JSON.stringify(v, null, 2);
  const out = `// AUTO-GENERATED by scripts/gen-mock.js — do not edit by hand.
// Re-run \`node scripts/gen-mock.js\` after changing the songs in src/eample-song.
import type { Track, Album, Artist, Playlist } from "./cloudflare";

// Set to false to use the real Cloudflare backend instead of these sample songs.
export const USE_MOCK_DATA = true;

export const MOCK_TRACKS: Track[] = ${J(tracks)};

export const MOCK_PLAYLISTS: Playlist[] = ${J(playlists)};

export const MOCK_CATEGORY_COUNTS: { category: string; count: number }[] = ${J(categoryCounts)};

export const MOCK_ALBUMS: Album[] = ${J(albums)};

export const MOCK_ARTISTS: Artist[] = ${J(artists)};
`;
  fs.writeFileSync(path.join(ROOT, "src", "lib", "mockData.ts"), out, "utf8");
  console.log(`✓ Generated ${tracks.length} tracks, ${albums.length} albums, ${artists.length} artists.`);
  console.log(`  Covers written to public/covers/ (${Object.keys(albumCover).length} album covers).`);
})().catch((e) => { console.error(e); process.exit(1); });
